### PR TITLE
[Reviewer: Andy] Backport processinstance.cpp from the GR branch

### PR DESCRIPTION
**Pull request by rkday-pro**
As discussed, I'm going to merge this, then merge master into 3-site-gr, then use this infrastructure in https://github.com/Metaswitch/clearwater-fv-test/pull/30.

### CODE REVIEW

**Comment by bossmc** [comment]
Hmmm... You possibly don't want to pull in the Memcached/Astaire code (in particular Astaire only has some of the used command-line parameters in the 3-site GR branch).  Maybe it's ok, since we'll never invoke either instance in dev/master?

**Comment by bossmc** [comment]
Otherwise fine.

**Comment by rkday-pro** [comment]
I want it copied verbatim to avoid merge conflicts - I'm happy to keep that unused code in master for that purpose.

**Comment by rkday-pro** [comment]
Actually, we're probably more prone to merge conflicts if people update the memcached code in one place but not the other, so I've decided to risk deleting it.

**Pull request merged**
